kulup/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace kulup.Controllers;

public class ContactController : Controller
{


    public IActionResult Index()
    {
        return View();
    }
}

kulup/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using kulup.Models;

namespace kulup.Controllers;


public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }


    public IActionResult Index()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

kulup/Controllers/LoginController.cs
using kulup.Data;
using kulup.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace kulup.Controllers;


public class LoginController : Controller
{
    private readonly UygulamaDbContext _context;
    public LoginController(UygulamaDbContext context)
    {
        _context = context;
    }

    // GET:Login
    public IActionResult Index()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Login(LoginModel model)
    {
        if (ModelState.IsValid)
        {
            var user = await _context.Members.FirstOrDefaultAsync(u => u.Email == model.Email && u.Sifre == model.Password);
            if (user !=null)
            {
                return RedirectToAction("Home","Index");
            }

            ModelState.AddModelError(string.Empty, "Kullanıcı adı veya şifre hatalı.");
        }
        return View("Index", model);
    }

}

kulup/Controllers/MemberController.cs
using kulup.Data;
using kulup.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace kulup.Controllers;

public class MemberController : Controller
{

    private readonly UygulamaDbContext _context;
    public MemberController(UygulamaDbContext context)
    {
        _context = context;
    }

    public async Task<IActionResult> Index()
    {
        var users = await _context.Members
            .Select(u => new Member
            {
                Id = u.Id,
                AdSoyad = u.AdSoyad,
                Email = u.Email,
                Telefon = u.Telefon.TrimStart('0'), // Telefon numarasındaki baştaki sıfırı kaldır
                Kulup = u.Kulup,
                CreatedAt = u.CreatedAt
            })
            .ToListAsync(); // Veritabanındaki kullanıcıları al

        return View(users); // Veriyi View'a gönder
    }


}

kulup/Controllers/RegisterController.cs
using kulup.Data;
using kulup.Models;
using Microsoft.AspNetCore.Mvc;

namespace kulup.Controllers
{
    public class RegisterController : Controller
    {

        private readonly UygulamaDbContext _context;
        public RegisterController(UygulamaDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Register(Member model)
        {
            if (ModelState.IsValid)
            {
                model.CreatedAt = DateTime.Now;
                // veri tabanına ekleme işlemi 
                _context.Members.Add(model);
                await _context.SaveChangesAsync();

                return RedirectToAction("Index", "Home");
            }else{
                return View(model);
            }
        }
    }
}

kulup/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Ana Sayfa";
}

<style>
    body {
        background: linear-gradient(135deg,
                #6a11cb 0%,
                #2575fc 100%);
        /* Genel background gradient */
    }
</style>

<header>
    <h2>Kulüp Üyelikleri Takip Sistemi</h2>
</header>

<main>
    <div class="button-container">
        <a asp-controller="Register" asp-action="Index" class="action-button"><i class="fas fa-user-plus"></i> Üye
            Ol</a>
        @* <a asp-controller="Login" asp-action="Index" class="action-button"><i class="fas fa-sign-in-alt"></i> Giriş
            Yap</a> *@
        <a asp-controller="Member" asp-action="Index" class="action-button"><i class="fas fa-users"></i></i>Mevcut
            Üyeleri Görüntüle</a>
        <a asp-controller="Contact" asp-action="Index" class="action-button"><i class="fas fa-envelope"></i>
            İletişim</a>
        <a asp-controller="Admin" asp-action="Home" target="_blank" class="action-button"><i class="fa-solid fa-lock"></i> Yönetici Paneli</a>
    </div>
</main>